"""Add province and tax_profile to Business

Revision ID: f816db6adf18
Revises: a7de1b16b25f
Create Date: 2026-02-05 14:38:33.705608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f816db6adf18'
down_revision: Union[str, Sequence[str], None] = 'a7de1b16b25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('businesses', sa.Column('province', sa.String(length=10), nullable=True))
    op.add_column('businesses', sa.Column('tax_profile', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('businesses', 'tax_profile')
    op.drop_column('businesses', 'province')
    # ### end Alembic commands ###
